# Generated by Django 3.2.13 on 2022-06-30 07:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cop',
            fields=[
                ('cop_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cop_name', models.CharField(blank=True, default='', max_length=100)),
                ('region', models.CharField(blank=True, default='korea', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('post_id', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, default='', max_length=100)),
                ('money', models.IntegerField(default=1000000)),
                ('tech', models.CharField(blank=True, default='', max_length=100)),
                ('content', models.TextField(default='', null=True)),
                ('cop_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cop')),
            ],
        ),
    ]
