# Generated by Django 3.2.13 on 2022-07-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.CharField(blank=True, default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
