# Generated by Django 3.2.13 on 2022-06-28 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cop_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
    ]
