# Generated by Django 3.2.13 on 2022-08-05 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_company_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='user',
            new_name='user_id',
        ),
    ]
