# Generated by Django 3.2.13 on 2022-06-29 07:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cop',
            name='id',
        ),
        migrations.AddField(
            model_name='cop',
            name='cop_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cop',
            name='cop_name',
            field=models.CharField(default='cop', max_length=100),
        ),
        migrations.AddField(
            model_name='cop',
            name='region',
            field=models.CharField(default='korea', max_length=100),
        ),
    ]
