# Generated by Django 3.2.13 on 2022-09-27 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_image', models.ImageField(blank=True, upload_to='pixel_converter/img')),
                ('result', models.ImageField(blank=True, upload_to='pixel_converter/results')),
            ],
        ),
    ]
